### ISSUE TITLE
In which language is coded the plugin?

### ISSUE THREAD

**Issue by GeMesoft** [gerhardol/trails#33]
Hello gerhardol, 
i was planning to develop a Sporttracks plugin.

Everything looks like c# and Visual Studio solution, but this kind of things exceed my knowledge:
bool p = TryParseFloat(val, NumberStyles.Any, **out float result);**

My vs2015 raise me an error and also, i don't find the definition for the result variable. This is the first time that i see  a inline function definition for a variable.

I was fighting all the day to get use to the api and the interfaces...

At this moment, and after one day searching the web, and investigating in the sporttracks forum, i realize that is to much effort for me to start without any documentation of the API neither any example of it and everything looks like all the developers gave up most of the plugins.

Best Regards,
Luis aka GeMe.

**Comment by gerhardol** [comment]
This is C#7 syntax
https://blogs.msdn.microsoft.com/dotnet/2016/08/24/whats-new-in-csharp-7-0/

Use VS2017 for C#7 (may be possible in VS2015 too, but I have no details).

Closing, as this issue not really is about the plugin, will update the wiki
